/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.summer.sdt.internal.compiler.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
//  /** RegularExpression Id. */
//  int SINGLE_LINE_COMMENT = 8;
//  /** RegularExpression Id. */
//  int FORMAL_COMMENT = 9;
//  /** RegularExpression Id. */
//  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int ABSTRACT = 12;
  /** RegularExpression Id. */
  int ASSERT = 13;
  /** RegularExpression Id. */
  int BOOLEAN = 14;
  /** RegularExpression Id. */
  int BREAK = 15;
  /** RegularExpression Id. */
  int BYTE = 16;
  /** RegularExpression Id. */
  int CASE = 17;
  /** RegularExpression Id. */
  int CATCH = 18;
  /** RegularExpression Id. */
  int CHAR = 19;
  /** RegularExpression Id. */
  int CLASS = 20;
  /** RegularExpression Id. */
  int CONST = 21;
  /** RegularExpression Id. */
  int CONTINUE = 22;
  /** RegularExpression Id. */
  int DEFAULT_ = 23;
  /** RegularExpression Id. */
  int DO = 24;
  /** RegularExpression Id. */
  int DOUBLE = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int ENUM = 27;
  /** RegularExpression Id. */
  int EXTENDS = 28;
  /** RegularExpression Id. */
  int FALSE = 29;
  /** RegularExpression Id. */
  int FINAL = 30;
  /** RegularExpression Id. */
  int FINALLY = 31;
  /** RegularExpression Id. */
  int FLOAT = 32;
  /** RegularExpression Id. */
  int FOR = 33;
  /** RegularExpression Id. */
  int GOTO = 34;
  /** RegularExpression Id. */
  int IF = 35;
  /** RegularExpression Id. */
  int IMPLEMENTS = 36;
  /** RegularExpression Id. */
  int IMPORT = 37;
  /** RegularExpression Id. */
  int INSTANCEOF = 38;
  /** RegularExpression Id. */
  int INT = 39;
  /** RegularExpression Id. */
  int INTERFACE = 40;
  /** RegularExpression Id. */
  int LONG = 41;
  /** RegularExpression Id. */
  int NATIVE = 42;
  /** RegularExpression Id. */
  int NEW = 43;
  /** RegularExpression Id. */
  int NULL = 44;
  /** RegularExpression Id. */
  int PACKAGE = 45;
  /** RegularExpression Id. */
  int PRIVATE = 46;
  /** RegularExpression Id. */
  int PROTECTED = 47;
  /** RegularExpression Id. */
  int PUBLIC = 48;
  /** RegularExpression Id. */
  int RETURN = 49;
  /** RegularExpression Id. */
  int SHORT = 50;
  /** RegularExpression Id. */
  int STATIC = 51;
  /** RegularExpression Id. */
  int STRICTFP = 52;
  /** RegularExpression Id. */
  int SUPER = 53;
  /** RegularExpression Id. */
  int SWITCH = 54;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 55;
  /** RegularExpression Id. */
  int THIS = 56;
  /** RegularExpression Id. */
  int THROW = 57;
  /** RegularExpression Id. */
  int THROWS = 58;
  /** RegularExpression Id. */
  int TRANSIENT = 59;
  /** RegularExpression Id. */
  int TRUE = 60;
  /** RegularExpression Id. */
  int TRY = 61;
  /** RegularExpression Id. */
  int VOID = 62;
  /** RegularExpression Id. */
  int VOLATILE = 63;
  /** RegularExpression Id. */
  int WHILE = 64;
  /** RegularExpression Id. */
  int MODULE = 65;
  /** RegularExpression Id. */
  int EXPORT = 66;
  /** RegularExpression Id. */
  int REF = 67;
  /** RegularExpression Id. */
  int OUT = 68;
  /** RegularExpression Id. */
  int GET = 69;
  /** RegularExpression Id. */
  int SET = 70;
  /** RegularExpression Id. */
  int ADD = 71;
  /** RegularExpression Id. */
  int REMOVE = 72;
  /** RegularExpression Id. */
  int EVENT = 73;
  /** RegularExpression Id. */
  int FUNCTION = 74;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 75;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 76;
  /** RegularExpression Id. */
  int HEX_LITERAL = 77;
  /** RegularExpression Id. */
  int BINARY_LITERAL = 78;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 79;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 80;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 81;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 82;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 83;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 84;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 85;
  /** RegularExpression Id. */
  int STRING_LITERAL = 86;
  /** RegularExpression Id. */
  int IDENTIFIER = 87;
  /** RegularExpression Id. */
  int LETTER = 88;
  /** RegularExpression Id. */
  int PART_LETTER = 89;
  /** RegularExpression Id. */
  int LPAREN = 90;
  /** RegularExpression Id. */
  int RPAREN = 91;
  /** RegularExpression Id. */
  int LBRACE = 92;
  /** RegularExpression Id. */
  int RBRACE = 93;
  /** RegularExpression Id. */
  int LBRACKET = 94;
  /** RegularExpression Id. */
  int RBRACKET = 95;
  /** RegularExpression Id. */
  int SEMICOLON = 96;
  /** RegularExpression Id. */
  int COMMA = 97;
  /** RegularExpression Id. */
  int DOT = 98;
  /** RegularExpression Id. */
  int AT = 99;
  /** RegularExpression Id. */
  int EQUAL = 100;
  /** RegularExpression Id. */
  int LESS = 101;
  /** RegularExpression Id. */
  int NOT = 102;
  /** RegularExpression Id. */
  int TWIDDLE = 103;
  /** RegularExpression Id. */
  int QUESTION = 104;
  /** RegularExpression Id. */
  int COLON = 105;
  /** RegularExpression Id. */
  int EQUAL_EQUAL = 106;
  /** RegularExpression Id. */
  int LESS_EQUAL = 107;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 108;
  /** RegularExpression Id. */
  int NOT_EQUAL = 109;
  /** RegularExpression Id. */
  int OR_OR = 110;
  /** RegularExpression Id. */
  int AND_AND = 111;
  /** RegularExpression Id. */
  int PLUS_PLUS = 112;
  /** RegularExpression Id. */
  int MINUS_MINUS = 113;
  /** RegularExpression Id. */
  int PLUS = 114;
  /** RegularExpression Id. */
  int MINUS = 115;
  /** RegularExpression Id. */
  int MULTIPLY = 116;
  /** RegularExpression Id. */
  int DIVIDE = 117;
  /** RegularExpression Id. */
  int AND = 118;
  /** RegularExpression Id. */
  int OR = 119;
  /** RegularExpression Id. */
  int XOR = 120;
  /** RegularExpression Id. */
  int REMAINDER = 121;
  /** RegularExpression Id. */
  int LEFT_SHIFT = 122;
  /** RegularExpression Id. */
  int PLUS_EQUAL = 123;
  /** RegularExpression Id. */
  int MINUS_EQUAL = 124;
  /** RegularExpression Id. */
  int MULTIPLY_EQUAL = 125;
  /** RegularExpression Id. */
  int DIVIDE_EQUAL = 126;
  /** RegularExpression Id. */
  int AND_EQUAL = 127;
  /** RegularExpression Id. */
  int OR_EQUAL = 128;
  /** RegularExpression Id. */
  int XOR_EQUAL = 129;
  /** RegularExpression Id. */
  int REMAINDER_EQUAL = 130;
  /** RegularExpression Id. */
  int LEFT_SHIFT_EQUAL = 131;
  /** RegularExpression Id. */
  int RIGHT_SHIFT_EQUAL = 132;
  /** RegularExpression Id. */
  int UNSIGNED_RIGHT_SHIFT_EQUAL = 133;
  /** RegularExpression Id. */
  int ELLIPSIS = 134;
  /** RegularExpression Id. */
  int UNSIGNED_RIGHT_SHIFT = 135;
  /** RegularExpression Id. */
  int RIGHT_SHIFT = 136;
  /** RegularExpression Id. */
  int GREATER = 137;
  /** RegularExpression Id. */
  int STUFF_TO_IGNORE = 139;
  
  int  DOUBLE_LITERAL = 140;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 11>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"module\"",
    "\"export\"",
    "\"ref\"",
    "\"out\"",
    "\"get\"",
    "\"set\"",
    "\"add\"",
    "\"remove\"",
    "\"event\"",
    "\"function\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<BINARY_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOAT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"\\u001a\"",
    "<STUFF_TO_IGNORE>",
    "\"->\"",
  };

}
